export default {
    routes:[{
        title:'机构管理',
        icon:'',
        children:[{
            title:'新增机构',
            path:'/main/addGov',
            component:null,
            show:true
        },{
            title:'编辑机构',
            path:'/main/editGov/:id?',
            component:null,
            show:false
        },{
            title:'机构详情',
            path:'/main/govDetail/:id?',
            component:null,
            show:false
        }]
    },{
        title:'教务管理',
        icon:'',
        children:[{
            title:'课程管理',
            children:[{
                title:'新建课程',
                path:'/main/addPro',
                component:null,
                show:true
            },{
                title:'编辑课程',
                path:'/main/editPro/:id?',
                component:null,
                show:false
            },{
                title:'异常提示',
                path:'/main/proError',
                component:null,
                show:false
            }]
        },{
            title:'班级管理',
            children:[{
                title:'新建班级',
                path:'/main/addClass',
                component:null,
                show:true
            },{
                title:'编辑班级',
                path:'/main/editClass/"id?',
                component:null,
                show:false
            },{
                title:'班级详情',
                path:'/main/classDetail',
                component:null,
                show:false
            }]
        }]
    }]
}